/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 17, 2009 19:23:44
 *
 *     -  From the grammar source file : .//LexWhenPredTree.g
 *     -                            On : 2011-03-12 11:53:43
 *     -           for the tree parser : LexWhenPredTreeTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <stdlib.h>
    #include <string.h>
    #include <antlr3.h>
    #include "../emerson/Util.h"

    #define APPLEX(s) program_string_lex->append(program_string_lex, s);

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "LexWhenPredTree.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pLexWhenPredTree_##scope##_SCOPE
#define SCOPE_STACK(scope)  pLexWhenPredTree_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pLexWhenPredTree_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO		
#undef		SEEK    
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   LexWhenPredTreeTokenNames[51+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "LTERM",
        (pANTLR3_UINT8) "PROG",
        (pANTLR3_UINT8) "WHEN_PRED_BLOCK",
        (pANTLR3_UINT8) "DOTTED_IDENTIFIER",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "Identifier",
        (pANTLR3_UINT8) "StringLiteral",
        (pANTLR3_UINT8) "NumericLiteral",
        (pANTLR3_UINT8) "DoubleStringCharacter",
        (pANTLR3_UINT8) "SingleStringCharacter",
        (pANTLR3_UINT8) "EscapeSequence",
        (pANTLR3_UINT8) "CharacterEscapeSequence",
        (pANTLR3_UINT8) "HexEscapeSequence",
        (pANTLR3_UINT8) "UnicodeEscapeSequence",
        (pANTLR3_UINT8) "SingleEscapeCharacter",
        (pANTLR3_UINT8) "NonEscapeCharacter",
        (pANTLR3_UINT8) "EscapeCharacter",
        (pANTLR3_UINT8) "DecimalDigit",
        (pANTLR3_UINT8) "HexDigit",
        (pANTLR3_UINT8) "DecimalLiteral",
        (pANTLR3_UINT8) "HexIntegerLiteral",
        (pANTLR3_UINT8) "ExponentPart",
        (pANTLR3_UINT8) "IdentifierStart",
        (pANTLR3_UINT8) "IdentifierPart",
        (pANTLR3_UINT8) "UnicodeLetter",
        (pANTLR3_UINT8) "UnicodeDigit",
        (pANTLR3_UINT8) "UnicodeConnectorPunctuation",
        (pANTLR3_UINT8) "UnicodeCombiningMark",
        (pANTLR3_UINT8) "Comment",
        (pANTLR3_UINT8) "LineComment",
        (pANTLR3_UINT8) "WhiteSpace",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "'-'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'['",
        (pANTLR3_UINT8) "']'",
        (pANTLR3_UINT8) "'!'",
        (pANTLR3_UINT8) "'='",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'/'",
        (pANTLR3_UINT8) "'>'",
        (pANTLR3_UINT8) "'<'",
        (pANTLR3_UINT8) "'%'",
        (pANTLR3_UINT8) "'&'",
        (pANTLR3_UINT8) "'|'",
        (pANTLR3_UINT8) "'^'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'",
        (pANTLR3_UINT8) "';'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static pANTLR3_STRING	program    (pLexWhenPredTree ctx);
static void	sourceElements    (pLexWhenPredTree ctx);
static void	sourceElement    (pLexWhenPredTree ctx);
static void	whenPredStatement    (pLexWhenPredTree ctx);
static void	identifier    (pLexWhenPredTree ctx);
static void	dottedIdentifier    (pLexWhenPredTree ctx);
static void	literal    (pLexWhenPredTree ctx);
static void	LexWhenPredTreeFree(pLexWhenPredTree ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = ".//LexWhenPredTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new LexWhenPredTree parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pLexWhenPredTree
LexWhenPredTreeNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return LexWhenPredTreeNewSSD(instream, NULL);
}

/** \brief Create a new LexWhenPredTree parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pLexWhenPredTree
LexWhenPredTreeNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pLexWhenPredTree ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pLexWhenPredTree) ANTLR3_CALLOC(1, sizeof(LexWhenPredTree));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in LexWhenPredTree.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);
    /* Install the implementation of our LexWhenPredTree interface
     */
    ctx->program	= program;
    ctx->sourceElements	= sourceElements;
    ctx->sourceElement	= sourceElement;
    ctx->whenPredStatement	= whenPredStatement;
    ctx->identifier	= identifier;
    ctx->dottedIdentifier	= dottedIdentifier;
    ctx->literal	= literal;
    ctx->free			= LexWhenPredTreeFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = LexWhenPredTreeTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 LexWhenPredTreeFree(pLexWhenPredTree ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this tree parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return LexWhenPredTreeTokenNames; 
}


        pANTLR3_STRING program_string_lex;

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_PROG_in_program81  */
static	ANTLR3_BITWORD FOLLOW_PROG_in_program81_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PROG_in_program81	= { FOLLOW_PROG_in_program81_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sourceElements_in_program110  */
static	ANTLR3_BITWORD FOLLOW_sourceElements_in_program110_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_sourceElements_in_program110	= { FOLLOW_sourceElements_in_program110_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sourceElement_in_sourceElements169  */
static	ANTLR3_BITWORD FOLLOW_sourceElement_in_sourceElements169_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_sourceElement_in_sourceElements169	= { FOLLOW_sourceElement_in_sourceElements169_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_whenPredStatement_in_sourceElement222  */
static	ANTLR3_BITWORD FOLLOW_whenPredStatement_in_sourceElement222_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_whenPredStatement_in_sourceElement222	= { FOLLOW_whenPredStatement_in_sourceElement222_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHEN_PRED_BLOCK_in_whenPredStatement266  */
static	ANTLR3_BITWORD FOLLOW_WHEN_PRED_BLOCK_in_whenPredStatement266_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_WHEN_PRED_BLOCK_in_whenPredStatement266	= { FOLLOW_WHEN_PRED_BLOCK_in_whenPredStatement266_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_whenPredStatement296  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_whenPredStatement296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000048) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_whenPredStatement296	= { FOLLOW_identifier_in_whenPredStatement296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_whenPredStatement_in_whenPredStatement360  */
static	ANTLR3_BITWORD FOLLOW_whenPredStatement_in_whenPredStatement360_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000048) };
static  ANTLR3_BITSET_LIST FOLLOW_whenPredStatement_in_whenPredStatement360	= { FOLLOW_whenPredStatement_in_whenPredStatement360_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_identifier438  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_identifier438_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_identifier438	= { FOLLOW_IDENTIFIER_in_identifier438_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Identifier_in_identifier466  */
static	ANTLR3_BITWORD FOLLOW_Identifier_in_identifier466_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000088) };
static  ANTLR3_BITSET_LIST FOLLOW_Identifier_in_identifier466	= { FOLLOW_Identifier_in_identifier466_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dottedIdentifier_in_identifier530  */
static	ANTLR3_BITWORD FOLLOW_dottedIdentifier_in_identifier530_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000088) };
static  ANTLR3_BITSET_LIST FOLLOW_dottedIdentifier_in_identifier530	= { FOLLOW_dottedIdentifier_in_identifier530_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOTTED_IDENTIFIER_in_dottedIdentifier629  */
static	ANTLR3_BITWORD FOLLOW_DOTTED_IDENTIFIER_in_dottedIdentifier629_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_DOTTED_IDENTIFIER_in_dottedIdentifier629	= { FOLLOW_DOTTED_IDENTIFIER_in_dottedIdentifier629_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Identifier_in_dottedIdentifier659  */
static	ANTLR3_BITWORD FOLLOW_Identifier_in_dottedIdentifier659_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000088) };
static  ANTLR3_BITSET_LIST FOLLOW_Identifier_in_dottedIdentifier659	= { FOLLOW_Identifier_in_dottedIdentifier659_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dottedIdentifier_in_dottedIdentifier723  */
static	ANTLR3_BITWORD FOLLOW_dottedIdentifier_in_dottedIdentifier723_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000088) };
static  ANTLR3_BITSET_LIST FOLLOW_dottedIdentifier_in_dottedIdentifier723	= { FOLLOW_dottedIdentifier_in_dottedIdentifier723_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_StringLiteral_in_literal818  */
static	ANTLR3_BITWORD FOLLOW_StringLiteral_in_literal818_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_StringLiteral_in_literal818	= { FOLLOW_StringLiteral_in_literal818_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NumericLiteral_in_literal835  */
static	ANTLR3_BITWORD FOLLOW_NumericLiteral_in_literal835_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NumericLiteral_in_literal835	= { FOLLOW_NumericLiteral_in_literal835_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start program
 * .//LexWhenPredTree.g:36:1: program returns [pANTLR3_STRING s] : ^( PROG sourceElements ) ;
 */
static pANTLR3_STRING
program(pLexWhenPredTree ctx)
{   
    pANTLR3_STRING s = NULL;

    /* Initialize rule variables
     */


    {
        // .//LexWhenPredTree.g:37:2: ( ^( PROG sourceElements ) )
        // .//LexWhenPredTree.g:37:3: ^( PROG sourceElements )
        {
             MATCHT(PROG, &FOLLOW_PROG_in_program81); 
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }
            if (HASFAILED())
            {
                return s;
            }

            if ( BACKTRACKING==0 ) 
            {

                                pANTLR3_STRING_FACTORY factory = antlr3StringFactoryNew();
                                program_string_lex = factory->newRaw(factory);
                                APPLEX("\n");
                                //open when_watched_list
                                APPLEX("util.create_when_watched_list([");
                            
            }

            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }
            if (HASFAILED())
            {
                return s;
            }
            FOLLOWPUSH(FOLLOW_sourceElements_in_program110);
            sourceElements(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }
            if (HASFAILED())
            {
                return s;
            }
            if ( BACKTRACKING==0 ) 
            {

                                //close when_watched_list
                                APPLEX("]);");
                            
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }
            if (HASFAILED())
            {
                return s;
            }
            if ( BACKTRACKING==0 ) 
            {

                            s = program_string_lex;
                        
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return s;
}
/* $ANTLR end program */

/** 
 * $ANTLR start sourceElements
 * .//LexWhenPredTree.g:56:1: sourceElements : ( sourceElement )+ ;
 */
static void
sourceElements(pLexWhenPredTree ctx)
{   
    /* Initialize rule variables
     */


    {
        // .//LexWhenPredTree.g:57:5: ( ( sourceElement )+ )
        // .//LexWhenPredTree.g:57:6: ( sourceElement )+
        {
            // .//LexWhenPredTree.g:57:6: ( sourceElement )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == WHEN_PRED_BLOCK) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // .//LexWhenPredTree.g:58:9: sourceElement
            	        {
            	            FOLLOWPUSH(FOLLOW_sourceElement_in_sourceElements169);
            	            sourceElement(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulesourceElementsEx;
            	            }
            	            if (HASFAILED())
            	            {
            	                return ;
            	            }
            	            if ( BACKTRACKING==0 ) 
            	            {

            	                            //closes the last paren associated with util.create_when_watched_item
            	                            APPLEX(")");
            	                        
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		if (BACKTRACKING>0)
            		{
            		    FAILEDFLAG = ANTLR3_TRUE; 
            		    return ;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulesourceElementsEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesourceElementsEx; /* Prevent compiler warnings */
    rulesourceElementsEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end sourceElements */

/** 
 * $ANTLR start sourceElement
 * .//LexWhenPredTree.g:66:1: sourceElement : ( whenPredStatement ) ;
 */
static void
sourceElement(pLexWhenPredTree ctx)
{   
    /* Initialize rule variables
     */


    {
        // .//LexWhenPredTree.g:67:5: ( ( whenPredStatement ) )
        // .//LexWhenPredTree.g:68:5: ( whenPredStatement )
        {
            // .//LexWhenPredTree.g:68:5: ( whenPredStatement )
            // .//LexWhenPredTree.g:69:9: whenPredStatement
            {
                FOLLOWPUSH(FOLLOW_whenPredStatement_in_sourceElement222);
                whenPredStatement(ctx);

                FOLLOWPOP();
                if  (HASEXCEPTION())
                {
                    goto rulesourceElementEx;
                }
                if (HASFAILED())
                {
                    return ;
                }
                if ( BACKTRACKING==0 ) 
                {
                     
                }

            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesourceElementEx; /* Prevent compiler warnings */
    rulesourceElementEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end sourceElement */

/** 
 * $ANTLR start whenPredStatement
 * .//LexWhenPredTree.g:75:1: whenPredStatement : ^( WHEN_PRED_BLOCK id1= identifier ( whenPredStatement )* ) ;
 */
static void
whenPredStatement(pLexWhenPredTree ctx)
{   
    /* Initialize rule variables
     */


    {
        // .//LexWhenPredTree.g:76:9: ( ^( WHEN_PRED_BLOCK id1= identifier ( whenPredStatement )* ) )
        // .//LexWhenPredTree.g:76:11: ^( WHEN_PRED_BLOCK id1= identifier ( whenPredStatement )* )
        {
             MATCHT(WHEN_PRED_BLOCK, &FOLLOW_WHEN_PRED_BLOCK_in_whenPredStatement266); 
            if  (HASEXCEPTION())
            {
                goto rulewhenPredStatementEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            if ( BACKTRACKING==0 ) 
            {

                                APPLEX("util.create_when_watched_item(['");
                            
            }

            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulewhenPredStatementEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            FOLLOWPUSH(FOLLOW_identifier_in_whenPredStatement296);
            identifier(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulewhenPredStatementEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {

                                APPLEX("]");
                            
            }

            // .//LexWhenPredTree.g:85:13: ( whenPredStatement )*

            for (;;)
            {
                int alt2=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA2_0 = LA(1);
                    if ( (LA2_0 == WHEN_PRED_BLOCK) ) 
                    {
                        alt2=1;
                    }

                }
                switch (alt2) 
                {
            	case 1:
            	    // .//LexWhenPredTree.g:86:17: whenPredStatement
            	    {
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                                APPLEX("),");
            	                            
            	        }
            	        FOLLOWPUSH(FOLLOW_whenPredStatement_in_whenPredStatement360);
            	        whenPredStatement(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulewhenPredStatementEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                            
            	        }

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulewhenPredStatementEx;
            }
            if (HASFAILED())
            {
                return ;
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulewhenPredStatementEx; /* Prevent compiler warnings */
    rulewhenPredStatementEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end whenPredStatement */

/** 
 * $ANTLR start identifier
 * .//LexWhenPredTree.g:96:1: identifier : ^( IDENTIFIER Identifier ( dottedIdentifier )* ) ;
 */
static void
identifier(pLexWhenPredTree ctx)
{   
    pANTLR3_BASE_TREE    Identifier1;

    /* Initialize rule variables
     */


    Identifier1       = NULL;

    {
        // .//LexWhenPredTree.g:97:9: ( ^( IDENTIFIER Identifier ( dottedIdentifier )* ) )
        // .//LexWhenPredTree.g:97:11: ^( IDENTIFIER Identifier ( dottedIdentifier )* )
        {
             MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_identifier438); 
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            if ( BACKTRACKING==0 ) 
            {

                            
            }

            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            Identifier1 = (pANTLR3_BASE_TREE) MATCHT(Identifier, &FOLLOW_Identifier_in_identifier466); 
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {

                                APPLEX((const char*)(Identifier1->getText(Identifier1))->chars);
                                APPLEX("'");
                            
            }

            // .//LexWhenPredTree.g:106:13: ( dottedIdentifier )*

            for (;;)
            {
                int alt3=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == DOTTED_IDENTIFIER) ) 
                    {
                        alt3=1;
                    }

                }
                switch (alt3) 
                {
            	case 1:
            	    // .//LexWhenPredTree.g:107:17: dottedIdentifier
            	    {
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                                APPLEX(",'");
            	                            
            	        }
            	        FOLLOWPUSH(FOLLOW_dottedIdentifier_in_identifier530);
            	        dottedIdentifier(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidentifierEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                            
            	        }

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidentifierEx; /* Prevent compiler warnings */
    ruleidentifierEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end identifier */

/** 
 * $ANTLR start dottedIdentifier
 * .//LexWhenPredTree.g:118:1: dottedIdentifier : ^( DOTTED_IDENTIFIER id1= Identifier ( dottedIdentifier )* ) ;
 */
static void
dottedIdentifier(pLexWhenPredTree ctx)
{   
    pANTLR3_BASE_TREE    id1;

    /* Initialize rule variables
     */


    id1       = NULL;

    {
        // .//LexWhenPredTree.g:119:9: ( ^( DOTTED_IDENTIFIER id1= Identifier ( dottedIdentifier )* ) )
        // .//LexWhenPredTree.g:119:11: ^( DOTTED_IDENTIFIER id1= Identifier ( dottedIdentifier )* )
        {
             MATCHT(DOTTED_IDENTIFIER, &FOLLOW_DOTTED_IDENTIFIER_in_dottedIdentifier629); 
            if  (HASEXCEPTION())
            {
                goto ruledottedIdentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            if ( BACKTRACKING==0 ) 
            {

                            
            }

            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruledottedIdentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            id1 = (pANTLR3_BASE_TREE) MATCHT(Identifier, &FOLLOW_Identifier_in_dottedIdentifier659); 
            if  (HASEXCEPTION())
            {
                goto ruledottedIdentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {

                                APPLEX((const char*)(id1->getText(id1))->chars);
                                APPLEX("'");   
                            
            }

            // .//LexWhenPredTree.g:128:13: ( dottedIdentifier )*

            for (;;)
            {
                int alt4=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA4_0 = LA(1);
                    if ( (LA4_0 == DOTTED_IDENTIFIER) ) 
                    {
                        alt4=1;
                    }

                }
                switch (alt4) 
                {
            	case 1:
            	    // .//LexWhenPredTree.g:129:17: dottedIdentifier
            	    {
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                                APPLEX(",'");
            	                            
            	        }
            	        FOLLOWPUSH(FOLLOW_dottedIdentifier_in_dottedIdentifier723);
            	        dottedIdentifier(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledottedIdentifierEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {

            	                            
            	        }

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruledottedIdentifierEx;
            }
            if (HASFAILED())
            {
                return ;
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruledottedIdentifierEx; /* Prevent compiler warnings */
    ruledottedIdentifierEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end dottedIdentifier */

/** 
 * $ANTLR start literal
 * .//LexWhenPredTree.g:144:1: literal : ( StringLiteral | NumericLiteral );
 */
static void
literal(pLexWhenPredTree ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  .//LexWhenPredTree.g:145:9: ( StringLiteral | NumericLiteral )
            
            ANTLR3_UINT32 alt5;

            alt5=2;


            {
                int LA5_0 = LA(1);
                if ( (LA5_0 == StringLiteral) ) 
                {
                    alt5=1;
                }
                else if ( (LA5_0 == NumericLiteral) ) 
                {
                    alt5=2;
                }
                else 
                {
                    if (BACKTRACKING>0)
                    {
                        FAILEDFLAG = ANTLR3_TRUE; 
                        return ;
                    }
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 5;
                    EXCEPTION->state        = 0;


                    goto ruleliteralEx;
                }
            }
            switch (alt5) 
            {
        	case 1:
        	    // .//LexWhenPredTree.g:145:11: StringLiteral
        	    {
        	         MATCHT(StringLiteral, &FOLLOW_StringLiteral_in_literal818); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleliteralEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return ;
        	        }
        	        if ( BACKTRACKING==0 ) 
        	        {

        	                      
        	        }

        	    }
        	    break;
        	case 2:
        	    // .//LexWhenPredTree.g:148:4: NumericLiteral
        	    {
        	         MATCHT(NumericLiteral, &FOLLOW_NumericLiteral_in_literal835); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleliteralEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return ;
        	        }
        	        if ( BACKTRACKING==0 ) 
        	        {

        	                      
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleliteralEx; /* Prevent compiler warnings */
    ruleliteralEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end literal */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
