// Copyright (c) 2012 Sirikata Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can
// be found in the LICENSE file.

#ifndef _SIRIKATA_MANUAL_PINTO_MANAGER_HPP_
#define _SIRIKATA_MANUAL_PINTO_MANAGER_HPP_

#include "PintoManagerBase.hpp"

#include <prox/manual/QueryHandler.hpp>
#include <prox/base/QueryEventListener.hpp>
#include <prox/base/LocationUpdateListener.hpp>

#include "PintoManagerLocationServiceCache.hpp"

#include <sirikata/core/prox/Defs.hpp>

namespace Sirikata {

/** ManualPintoManager responds to queries from space servers for a top-level
 *  tree, representing the highest-level aggregates. Each query has a cut,
 *  ManualPintoManager accepts commands to control it, and replicates data about
 *  nodes along and above the cut to the client space server.
 */
class ManualPintoManager
    : public PintoManagerBase,
      public Prox::QueryEventListener<ServerProxSimulationTraits, Prox::ManualQuery<ServerProxSimulationTraits> >
{
public:
    ManualPintoManager(PintoContext* ctx);
    virtual ~ManualPintoManager();

private:
    typedef Prox::ManualQueryHandler<ServerProxSimulationTraits> ProxQueryHandler;
    typedef Prox::ManualQuery<ServerProxSimulationTraits> Query;
    typedef Prox::QueryEvent<ServerProxSimulationTraits> QueryEvent;

    // PintoManagerBase overrides
    virtual void onConnected(Sirikata::Network::Stream* newStream);
    virtual void onInitialMessage(Sirikata::Network::Stream* stream);
    virtual void onRegionUpdate(Sirikata::Network::Stream* stream, BoundingSphere3f bounds);
    virtual void onMaxSizeUpdate(Sirikata::Network::Stream* stream, float32 ms);
    virtual void onQueryUpdate(Sirikata::Network::Stream* stream, const String& update);
    virtual void onDisconnected(Sirikata::Network::Stream* stream);


    // QueryEventListener Interface
    virtual void queryHasEvents(Query* query);

    // AggregateListener Overrides
    virtual void aggregateBoundsUpdated(ProxAggregator* handler, const ServerID& objid, const Vector3f& bnds_center, const float32 bnds_center_radius, const float32 max_obj_size);

    // Send a location update to subscribers of the given node
    void sendLocUpdate(ServerID about);


    // Command handlers
    virtual void commandProperties(const Command::Command& cmd, Command::Commander* cmdr, Command::CommandID cmdid);
    virtual void commandListHandlers(const Command::Command& cmd, Command::Commander* cmdr, Command::CommandID cmdid);
    virtual void commandForceRebuild(const Command::Command& cmd, Command::Commander* cmdr, Command::CommandID cmdid);
    virtual void commandListNodes(const Command::Command& cmd, Command::Commander* cmdr, Command::CommandID cmdid);


    // Tick the QueryHandler. We don't actually care about time since Servers
    // won't be in motion. Should only be called when the server data or query
    // data is updated.
    void tick();

    typedef std::tr1::unordered_set<ServerID> ServerSet;
    struct ClientData {
        ClientData()
         : query(NULL),
           seqno(0)
        {}

        Query* query;
        uint64 seqno;
        // Track copy of query results so we can clean up subscriptions
        ServerSet results;
    };
    std::tr1::unordered_map<Sirikata::Network::Stream*, ClientData> mClients;
    // Reverse index for queryHasEvents callbacks
    typedef std::tr1::unordered_map<Query*, Sirikata::Network::Stream*> ClientsByQuery;
    ClientsByQuery mClientsByQuery;
    // Index of subscribers generated by queries
    typedef std::tr1::unordered_set<Sirikata::Network::Stream*> ClientStreamSet;
    typedef std::tr1::unordered_map<ServerID, ClientStreamSet> ServerSubscriberMap;
    ServerSubscriberMap mServerSubscribers;
    // Single list of prox index IDs since we only have 1 querier -> all results
    // will use the same set of indices.
    typedef std::tr1::unordered_set<ProxIndexID> ProxIndexIDSet;
    ProxIndexIDSet mProxIndices;

    ProxQueryHandler* mQueryHandler;
    Time mLastTime;
    Duration mDt;
}; // class ManualPintoManager

} // namespace Sirikata

#endif //_SIRIKATA_MANUAL_PINTO_MANAGER_HPP_
