
#ifndef __SIRIKATA_JSFIELDS_HPP__
#define __SIRIKATA_JSFIELDS_HPP__

#define ADDRESSABLE_FIELD_COUNT 2
#define ADDRESSABLE_JSOBJSCRIPT_FIELD 0 
#define ADDRESSABLE_SPACEOBJREF_FIELD 1



#define JSHANDLER_FIELD_COUNT 2
#define JSHANDLER_JSOBJSCRIPT_FIELD    0
#define JSHANDLER_JSEVENTHANDLER_FIELD 1


#define PRESENCE_FIELD_COUNT 1
#define PRESENCE_FIELD 0
//SPACE_ID_FIELD 0
//#define PRESENCE_JSOBJSCRIPT_FIELD 1 


#endif
