
#ifndef __SIRIKATA_JSFIELDS_HPP__
#define __SIRIKATA_JSFIELDS_HPP__

#define ADDRESSABLE_FIELD_COUNT 2
#define ADDRESSABLE_JSOBJSCRIPT_FIELD 0 
#define ADDRESSABLE_SPACEOBJREF_FIELD 1



#define JSHANDLER_FIELD_COUNT 2
#define JSHANDLER_JSOBJSCRIPT_FIELD    0
#define JSHANDLER_JSEVENTHANDLER_FIELD 1


#define PRESENCE_FIELD_COUNT 1
#define PRESENCE_FIELD_PRESENCE 0

#define CONTEXT_TEMPLATE_FIELD_COUNT 1
#define CONTEXT_FIELD_CONTEXT_STRUCT 0


#define MATH_TEMPLATE_FIELD_COUNT 0


#define CONTEXT_TEMPLATE_FIELD_COUNT 1
#define CONTEXT_TEMPLATE_JSOBJSCRIPT_FIELD 0


#define SYSTEM_TEMPLATE_FIELD_COUNT 1
#define SYSTEM_TEMPLATE_JSOBJSCRIPT_FIELD 0



#define JSSIMOBJECT_TEMPLATE_FIELD_COUNT 2
#define JSSIMOBJECT_JSOBJSCRIPT_FIELD 0
#define JSSIMOBJECT_SIMULATION_FIELD 1

#define JSINVOKABLE_OBJECT_TEMPLATE_FIELD_COUNT 2
#define JSINVOKABLE_OBJECT_JSOBJSCRIPT_FIELD 0
#define JSINVOKABLE_OBJECT_SIMULATION_FIELD 1




#define VISIBLE_FIELD_COUNT 3
#define VISIBLE_JSOBJSCRIPT_FIELD 0
#define VISIBLE_SPACEOBJREF_FIELD 1
#define VISIBLE_TO_SPACEOBJREF_FIELD 2


#endif
