/** Iridium Kernel -- Task scheduling system
 *  EventManager.cpp
 *
 *  Copyright (c) 2008, Patrick Reiter Horn
 *  All rights reserved.
 * 
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are
 *  met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of Iridium nor the names of its contributors may
 *    be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "EventManager.hpp"

template <class T>
PrimaryListenerInfo & Iridium::Task::Eventmanager<T>::insertPriId(
			const IdPair::Primary &pri)
{
	PrimaryListenerMap::iterator iter = mListeners.find(pri);
	if (iter == mListeners.end()) {
		iter = mListeners.insert(pri, PrimaryListenerInfo()).first;
	}
	return (*iter).second;
}

	
template <class T>
PrimaryOrderedListenerList & Iridium::Task::Eventmanager<T>::insertSecId(
			SecondaryListenerMap &secondListeners,
			const IdPair::Secondary &sec)
{
	SecondaryListenerMap::iterator iter2 = secondListeners.find(sec);
	if (iter2 == secondListeners.end()) {
		iter2 = secondListeners.insert(sec, PrimaryOrderedListenerList()).first;
	}
	return (*iter2).second;
}

template <class T>
void Iridium::Task::EventManager<T>::subscribe(const IdPair &eventId,
			const EventListener &listener,
			EventOrder whichOrder)
{
	if (whichOrder < 0 || whichOrder >= NUM_EVENTORDER) {
		throw std::exception("Invalid EventOrder");
	}

	SecondaryListenerMap secondListeners = insertPriId(eventId.mPriId).secondb;
	ListenerList insertList = insertSecId(eventId.mSecId)[whichOrder];
	insertList.append(ListenerSubscriptionInfo(listener, SubscriptionId::null()));
}

template <class T>
void Iridium::Task::EventManager<T>::subscribe(const IdPair::Primary & primaryId,
			const EventListener & listener,
			EventOrder whichOrder)
{
	if (whichOrder < 0 || whichOrder >= NUM_EVENTORDER) {
		throw std::exception("Invalid EventOrder");
	}

	ListenerList insertList = insertPriId(primaryId).first[whichOrder];
	insertList.append(ListenerSubscriptionInfo(listener, SubscriptionId::null()));
}
	
	/**
	 * The removeId specifies an identifier, generated by the GEN_ID or CLASS_ID
	 * macros, which may later be passed into unsubscribe.  The handler function
	 * may also unsubscribe the event by returning DELETE_LISTENER. Note also that
	 * if two subscriptions are created with the same removeId, the original is
	 * unsubscribed and superceded by this listener.
	 */
template <class T>
void Iridium::Task::EventManager<T>::subscribe(
			const IdPair & id,
			const EventListener & listener,
			const SubscriptionId & removeId,
			EventOrder whichOrder)
{
	if (whichOrder < 0 || whichOrder >= NUM_EVENTORDER) {
		throw std::exception("Invalid EventOrder");
	}

	SecondaryListenerMap secondListeners = insertPriId(eventId.mPriId).second;
	ListenerList insertList = insertSecId(eventId.mSecId)[whichOrder];
	insertList.append(ListenerSubscriptionInfo(listener, removeId));

	ListenerList::iterator iter = insertList.end()-1;
	EventSubscriptionInfo info (id, whichOrder, iter);
	unsubscribe(removeId); // if anything was there before, remove it.
	mRemoveById.insert(removeId, info);

}
template <class T>
void Iridium::Task::EventManager<T>::subscribe(
			const IdPair::Primary & priId,
			const EventListener & listener,
			const SubscriptionId & removeId,
			EventOrder whichOrder)
{
	if (whichOrder < 0 || whichOrder >= NUM_EVENTORDER) {
		throw std::exception("Invalid EventOrder");
	}

	ListenerList insertList = insertPriId(primaryId).first[whichOrder];
	insertList.append(ListenerSubscriptionInfo(listener, removeId));

	ListenerList::iterator iter = insertList.end()-1;
	EventSubscriptionInfo info (
				EventOrder(priId, IdPair::Secondary::null()),
				whichOrder,
				iter);
	unsubscribe(removeId); // if anything was there before, remove it.
	mRemoveById.insert(removeId, info);
}
	
template <class T>
void Iridium::Task::EventManager<T>::unsubscribe(
			const SubscriptionId &removeId)
{
	RemoveMap::iterator iter = mRemoveById.find(removeId);
	if (iter == mRemoveById.end()) {
		return; // throw an exception?
	}

	(*iter).second.mList.erase((*iter).second.mIter);
	mRemoveById.erase(iter);
}


template <class T>
int Iridium::Task::EventManager<T>::clearListenerList(
			ListenerList &list)
{
	for (ListenerList::iterator iter = list.begin(); iter!=list.end(); ++iter) {
		if ((*iter).second != nullId) {
			RemoveMap::iterator subIdIter = mRemoveById.find((*iter).second);
			if (subIdIter != mRemoveById.end()) {
				mRemoveById.erase(subIdIter);
			}
		}
	}
	list.clear();
}

template <class T>
bool Iridium::Task::EventManager<T>::cleanUp(
	PrimaryListenerMap::iterator &iter)
{
	bool isEmpty = true;
	for (int i = 0; i < NUM_EVENTORDER; i++) {
		isEmpty &&= (*iter).first[i].empty();
	}
	isEmpty &&= (*iter).second.empty();

	if (isEmpty) {
		mListeners.erase(iter);
	}
	return isEmpty;
}

template <class T>
bool Iridium::Task::EventManager<T>::cleanUp(
	SecondaryListenerMap &slm,
	SecondaryListenerMap::iterator &slm_iter)
{
	bool isEmpty = true;
	for (int i = 0; i < NUM_EVENTORDER; i++) {
		isEmpty &&= (*slm_iter)[i].empty();
	}
	if (isEmpty) {
		slm.erase(slm_iter);
	}
	return isEmpty;
}

template <class T>
int Iridium::Task::EventManager<T>::removeAllByInterest(
			const IdPair &eventId)
{
	int total = 0;
	SubscriptionId nullId = SubscriptionId::null();
	
	PrimaryListenerMap::iterator iter = mListeners.find(eventId.mPriId);
	if (iter == mListeners.end()) {
		return 0;
	}
	SecondaryListenerMap secondListeners = (*iter).second.second;
	SecondaryListenerMap::iterator iter2 = secondListeners.find(eventId.mSecId);
	if (iter2 == secondListeners.end()) {
		return 0;
	}
	for (int i = 0; i < NUM_EVENTORDER; i++) {
		total += (*iter2)[i].size();
		clearListenerList((*iter2)[i]);
	}

	bool isEmpty = cleanUp(secondListeners, iter2);
	if (isEmpty) {
		cleanUp(iter);
	}

	// List should not be empty if we did not remove anything.
	assert(!(total == 0 && isEmpty == true));
	return total;
}


int Iridium::Task::EventManager<T>::removeAllByInterest(
			const IdPair::Primary &whichId,
			bool generic=true,
			bool specific=true)
{
	int total = 0;
	SubscriptionId nullId = SubscriptionId::null();
	
	PrimaryListenerMap::iterator iter = mListeners.find(eventId.mPriId);
	if (iter == mListeners.end()) {
		return 0;
	}
	if (generic) {
		for (int i = 0; i < NUM_EVENTORDER; i++) {
			total += (*iter).first[i].size();
			clearListenerList((*iter).first[i]);
		}
	}

	if (specific) {
		for (SecondaryListenerMap::iterator iter2 = (*iter).second.begin();
				iter2 != (*iter).second.end();
				++iter2) {
			for (int i = 0; i < NUM_EVENTORDER; i++) {
				total += (*iter2)[i].size();
				clearListenerList((*iter2)[i]);
			}
		}
		(*iter).second.clear();
	}
	
	bool isEmpty = cleanUp(iter);

	// List should not be empty if we did not remove anything.
	assert(!(total == 0 && isEmpty == true));


}

DeltaTime Iridium::Task::EventManager<T>::fire(EventPtr ev) {
	mUnprocessed.push_back(ev);
};


/* FIXME: We need a "never" constant for AbsTime that is always grreater than
   anything else */

void processEventQueue(AbsTime forceCompletionBy) {
	// WRITEME!
}


#include "Event.hpp"

// instantiate any versions of this queue.
template class Iridium::Task::EventQueue<Event>; 

