all:
#	g++ -fprofile-generate -I. -I ../../include  *.cpp -I../../../dependencies/installed-xz/include ../../../dependencies/installed-xz/lib/liblzma.a -g -std=c++0x -pg -O3
#	g++ -fprofile-arcs -ftest-coverage -I. -I ../../include  *.cpp -I../../../dependencies/installed-xz/include -L../../../dependencies/installed-xz/lib -llzma -g -std=c++0x -pg -O3
	g++ -I. -I ../../include  *.cpp -I../../../dependencies/installed-xz/include -L../../../dependencies/installed-xz/lib -llzma -g -std=c++0x -O3
#	g++ -I. -I ../../include  *.cpp -I../../../dependencies/installed-xz/include -L../../../dependencies/installed-xz/lib -llzma -g -std=c++0x -O3 -pg
#	g++ -fprofile-use -I. -I ../../include  *.cpp -I../../../dependencies/installed-xz/include ../../../dependencies/installed-xz/lib/liblzma.a -g -std=c++0x -pg -O3